# Site settings
title: "Benji Lewis' Resume"
description: "My CV"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Benjamin G. Lewis"
resume_title:                   "Software Engineer"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "benji.g.lewis@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "+4453500920"
resume_contact_address:         "London, United Kingdom"

resume_header_contact_info:     "London, United Kingdom • +447453500920 • benji.g.lewis@gmail.com"
display_header_contact_info:    "false"

resume_header_intro: "
  <p>
    I am an engineer with a passion for <b>technology</b>, <b>design</b>, <b>leadership</b>, <b>people</b> and <b>making a difference in the world</b>. With my degree in electrical & computer engineering, as well as my experience as a full stack software engineer, I have developed a strong set of skills which are applicaple to a diverse set of problems.
  </p>
  <p>
    Having been in leadership positions and involved in youth movements growing up, I have also developed people skills. Which allow me to relate to others, understand their positions and lead them to success in what they are working with. I have applied this in leading projects proffessionally, as well as through informal coaching of other colleagues.
  </p>
  <p>
    My proffesional goal is to be involved in technological leadership. Architecting elegant and efficient solutions to difficult problems, and leading a team to achieve success in the implementation of these.
  </p>
"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     true
resume_section_links:           true
resume_section_associations:    true
resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/benjilewis"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/benjamin-lewis-ece"
  # resume_instagram_url:         "insert your Instagram URL here"
  resume_website_url:           "https://benji249.wixsite.com/portfolio"
  # resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
